version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  # Spring Boot Application Service
  spring-app:
    image: nourchenh/projectdevopsspring:ImageSpringboot
    container_name: spring
    restart:  on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "8282:8282"
    depends_on:
      - mysql

volumes:
  db:
