version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  # Spring Boot Application Service
  spring-app:
    image: amenbenkhalifa/devops_project1:SpringImage
    container_name: spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/achatdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "8282:8282"
    depends_on:
      - mysql
volumes:
  db: