version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3307"
    volumes:
      - db:/var/lib/mysql

  # Spring Boot Application Service
  spring-app:
    image: nourchenh/achat1:BackendImage
    container_name: spring
    restart:  on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "8282:8282"
    depends_on:
      - mysql
  angular-app:
    image: nourchenh/devops_project1:AngularImage
    container_name: angular
    restart: on-failure
    ports:
      - "4200:80"
    depends_on:
      - spring-app
volumes:
  db:
