version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABaSE: achat_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetworkk
  achat-backend:
    depends_on:
      - mysqldb
    image: aziz64/achat:1.0.0
    container_name: backend
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
  "spring.datasource.url": "jdbc:mysql://mysqldb:3306/achat_db?createDatabaseIfNotExist=true",
  "spring.datasource.username": "root",
  "spring.datasource.password": "root",
  "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
  "spring.jpa.hibernate.ddl-auto": "update"
}'
    networks:
      - mynetworkk

    stdin_open: true
    tty: true

  front:
    image: frontaziz
    container_name: frontend
    restart: on-failure
    depends_on:
      - achat-backend
    ports:
      - 8082:4200
    networks:
      - mynetworkk
volumes:
  db:
networks:
  mynetworkk:
    driver: bridge

