version: '3'
services:
  mysqldb:
    image: mysql:8.0.32
    container_name: mysqldb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: devopsback
    networks:
      - mon_reseau
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
      - mysqldb
    networks:
      - mon_reseau
    ports:
      - "8083:8282"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/devopsback
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""

  angular-frontend:
    image: 23153122e351/front:v2
    container_name: angular-frontend
    networks:
      - mon_reseau
    ports:
      - "4200:4200"  # Adjust the port as needed for your Angular app

networks:
  mon_reseau:
    driver: bridge

volumes:
  mysql_data:
